version: '3.8'

services:
  database:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: manage_app_database
      MYSQL_ROOT_PASSWORD: Nguyenduyhoang2005
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: fashion_backend
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Nguyenduyhoang2005
      - DB_NAME=manage_app_database
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: fashion_frontend
    restart: always
    ports:
      - "80:80" # Chạy thẳng cổng Web
    depends_on:
      - backend

volumes:
  db_data: