version: '3.8'
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: manage_app_database
      MYSQL_ROOT_PASSWORD: Nguyenduyhoang2005
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/data/init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    # ... (Giữ nguyên)
    build: ./backend
    container_name: fashion_backend
    restart: always
    environment:
      - PYTHONUNBUFFERED=1  
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Nguyenduyhoang2005
      - DB_NAME=manage_app_database
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - database
    volumes:
      - ./backend:/app

  frontend:
    # ... (Giữ nguyên)
    build: ./frontend
    container_name: fashion_frontend
    restart: always
    # ports:
    #   - "80:80"
    depends_on:
      - backend
    # 4. Nginx (MỚI - Cổng chính HTTPS)
  nginx:
    image: nginx:alpine
    container_name: fashion_nginx
    restart: always
    ports:
      - "80:80"   # HTTP (Để chuyển hướng sang HTTPS)
      - "443:443" # HTTPS (SSL)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  # 5. Certbot (MỚI - Để lấy/gia hạn SSL miễn phí)
  certbot:
    image: certbot/certbot
    container_name: fashion_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
volumes:
  db_data: